[config]

[templates.waybar]
input_path = './templates/colors.css'
output_path = './files/waybar.css'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = './files/matugen.toml'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = './files/starship.toml'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = './files/theme.toml'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = './files/matugen.rasi'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = './files/matugen.conf'
