[general]
import = [ "~/.config/alacritty/carbonfox.toml" ]

[cursor]
style.shape = "Beam"
style.blinking = "Always"
vi_mode_style.shape = "Beam"
unfocused_hollow = false
blink_timeout = 0

[env]
TERM = "alacritty"

[font.normal]
family = "Iosevka Nerd Font"
style = "normal"

[font]
size = 13

[window]
decorations = "none"
opacity = 1
dynamic_title = true

[window.padding]
x = 15
y = 15
