#!/usr/bin/env bash

usage() {
    echo "Usage: $0 [OPTION] task"
    echo -e "\n[ARGS]"
    echo "    task         Name of the task to run. All tasks should be placed in ./tasks directory"
    echo "                 Only one task can be specified"
    echo -e "\n[OPTIONS]"
    echo "    -h, --help    Show this message"
}

if [ ! -d "./tasks" ]; then
    echo "'tasks' directory not found in $(dirname "$(readlink -f "$0")")"
    exit 1
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
    -h | --help)
        usage
        exit 0
        ;;
    *)
        break
        ;;
    esac
done

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi

TASK_NAME="$1"
TASK_SCRIPT="./tasks/$TASK_NAME"

GREEN="\033[0;32m"
RESET="\033[0m"

if [ -f "$TASK_SCRIPT" ] && [ -x "$TASK_SCRIPT" ]; then

    if ! "$TASK_SCRIPT"; then
        echo -e "Task '$TASK_NAME' failed\n"
        exit 1
    fi

    echo -e "${GREEN}Task '$TASK_NAME' completed${RESET}\n"
else
    echo -e "Task '$TASK_NAME' not found or is not executable\n"
    exit 1
fi
