#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <task_name>"
    exit 1
fi

TASK_NAME="$1"
TASK_SCRIPT="./tasks/$TASK_NAME"

GREEN="\033[0;32m"
RESET="\033[0m"

if [ -f "$TASK_SCRIPT" ] && [ -x "$TASK_SCRIPT" ]; then
    "$TASK_SCRIPT"

    if [ $? -ne 0 ]; then
        echo -e "Task '$TASK_NAME' failed\n"
        exit 1
    fi

    echo -e "${GREEN}Task '$TASK_NAME' completed${RESET}\n"
else
    echo -e "Task '$TASK_NAME' not found or is not executable\n"
    exit 1
fi
