theme = "carbonfox"
# theme = "ayu_evolve"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
