#!/usr/bin/env bash

while true; do
    read -p "Running all tasks is dangerous. Do you want to continue? (y/N): " answer
    answer=${answer:-n} # n if no input
    answer=${answer,,}  # to lowercase

    if [[ "$answer" == "y" ]]; then
        break
    elif [[ "$answer" == "n" ]]; then
        exit 1
    else
        echo "Invalid response"
    fi
done

exclude=(
    "$(basename "$0")"
    "common"
)

deps=()
while IFS= read -r file; do
    base_name="$(basename "$file")"
    if [[ ! " ${exclude[@]} " =~ " $base_name " ]]; then
        deps+=("$base_name")
    fi
done < <(find tasks -maxdepth 1 -type f)

source tasks/common
resolve_deps

# Task
echo "${deps[@]}"
