#!/usr/bin/env bash

deps=(
    intel
)

source tasks/common
resolve_deps

# Task
install_if_missing libglvnd Vulkan-Headers ffmpeg-devel \
    libdrm libva-devel libcap-devel \
    dbus-devel wayland-devel pipewire-devel \
    pulseaudio-devel mesa-vaapi

# This sucks
install_if_missing libX11-devel libXcomposite-devel libXrandr-devel \
    libXdamage-devel

install_if_missing base-devel meson cmake pkg-config

build_repo repo.dec05eba.com/gpu-screen-recorder \
    "rm -rf build" \
    "meson setup build" \
    "meson configure --prefix=/usr --buildtype=release -Dsystemd=false -Dnvidia_suspend_fix=false -Dstrip=true build" \
    "sudo ninja -C build install"
