#!/usr/bin/env bash

deps=(
    dbus
    hypr
)

source tasks/common
resolve_deps

# Task
install_if_missing greetd tuigreet

sudo mkdir -p /etc/greetd
sudo usermod -aG video _greeter

if [ ! -s /etc/greetd/config.toml ] || confirm "greetd config already exists. Overwrite?" "N"; then
    cat <<'EOF' | sudo tee "/etc/greetd/config.toml" >/dev/null
[terminal]
vt = 7

[default_session]
command = "tuigreet --remember --cmd 'dbus-run-session hyprland'"
user = "_greeter"
EOF
fi

enable_service greetd
