#!/usr/bin/env bash

deps=(
    go
    fonts
    dots/helix
)

source tasks/common
resolve_deps

# Task
install_if_missing base-devel helix nodejs taplo yamlfmt rust shfmt shellcheck clang-tools-extra19 lldb19

sudo npm i -g prettier
sudo npm i -g yaml-language-server@next
sudo npm i -g vscode-langservers-extracted
if [ ! -e "/usr/bin/bash-language-server" ]; then
    sudo npm install -g bash-language-server
else
    echo "bash-language-server is already installed in /usr/bin"
fi

cargo install --git https://github.com/euclio/mdpls
download_github_release "artempyanykh/marksman" "marksman-linux-x64" "/usr/bin/marksman"
sudo chmod +x /usr/bin/marksman
