#!/usr/bin/env bash

deps=(
    polkit
    seat
    intel
    fonts
    dots/hypr
)

source tasks/common
resolve_deps

# Task
repo="repository=https://raw.githubusercontent.com/Makrennel/hyprland-void/repository-x86_64-glibc"
if grep -rwxq "$repo" /etc/xbps.d/; then
    echo "hypr* repository found"
else
    cat <<EOF | sudo tee "/etc/xbps.d/hyprland-void.conf" >/dev/null
$repo
EOF
fi

sudo xbps-install -S

install_if_missing hyprland-devel hyprland-protocols xdg-desktop-portal-hyprland
install_if_missing hypridle hyprlock hyprpaper hyprpicker hyprland-qtutils
install_if_missing wl-clipboard grim slurp alacritty Waybar dunst udiskie brightnessctl

hyprpm update
hyprpm add https://github.com/hyprwm/hyprland-plugins
hyprpm enable hyprbars
