#!/usr/bin/env bash

deps=(
    dbus
    polkit
)

source tasks/common
resolve_deps

# Task

repo="repository=https://raw.githubusercontent.com/Makrennel/hyprland-void/repository-x86_64-glibc"
if [ rep -rwxq $repo /etc/xbps.d/ ]; then
    echo "hypr* repository found"
else
    cat <<EOF | sudo tee "/etc/xbps.d/hyprland-void.conf" >/dev/null
$repo
EOF
fi

sudo xbps-install -S

install_if_missing hyprland-devel hyprland-protocols
install_if_missing hypridle hyprlock hyprpaper hyprpicker
install_if_missing wl-clipboard
