#!/usr/bin/env bash

deps=()

source tasks/common
resolve_deps

# Task
if ! lspci | grep -i vga | grep -qi intel; then
    if confirm "Not running intel gpu. Skip this task?" "Y"; then
        exit 0
    fi
fi

install_if_missing intel-ucode
if confirm "Apply initramfs configuration changes?" "Y"; then
    sudo xbps-reconfigure --force linux"$(uname -a | awk '{print $3}' | awk -F. '{print $1"."$2}')"
    echo "Regenerated initramfs"
else
    echo "Skipped initramfs"
fi

install_if_missing mesa-intel-dri vulkan-loader intel-video-accel
