#!/usr/bin/env bash

deps=(
    iwd
)

source tasks/common
resolve_deps

# Task
install_if_missing cargo

build_repo github.com/e-tho/iwmenu \
    "cargo build --release" \
    "mkdir -p ~/.local/bin" \
    "cp -f target/release/iwmenu ~/.local/bin"

echo -e "\nMake sure ~/.local/bin is in your \$PATH"
