#!/usr/bin/env bash

deps=()

source tasks/common
resolve_deps

# Task
install_if_missing curl libayatana-appindicator

tmpdir=$(mktemp -d)

trap 'cd /tmp && rm -rf "$tmpdir"' EXIT

cd "$tmpdir" || exit

download_github_release "localsend/localsend" "x86-64.tar.gz" "localsend.tar.gz"

if ! tar -xzf "localsend.tar.gz"; then
    echo "Failed to extract archive"
    exit 1
fi

mkdir -p ~/.local/bin/localsend
cp -r localsend_app ~/.local/bin/localsend/localsend_app
cp -r data/ ~/.local/bin/localsend/
cp -r lib/ ~/.local/bin/localsend/

echo "Adding .desktop file to $HOME/.local/share/applications"
mkdir -p ~/.local/share/applications
cat <<'EOF' >~/.local/share/applications/localsend.desktop
[Desktop Entry]
Name=LocalSend
Icon=internet-chat
Comment=An open-source cross-platform alternative to AirDrop
Terminal=false
Exec=/usr/bin/env bash -c "exec $HOME/.local/bin/localsend/localsend_app"
Type=Application
Categories=Utility;FileTools;
EOF
