#!/usr/bin/env bash

deps=(
    dbus
)

source tasks/common
resolve_deps

# Task
if ! check_var DBUS_SESSION_BUS_ADDRESS; then
    echo "Session dbus is not provided"
    exit 1
fi

install_if_missing elogind
