#!/usr/bin/env bash

deps=(
    bash
    dots/yazi
)

source tasks/common
resolve_deps

# Task
install_if_missing yazi ffmpeg 7zip ouch jq fd \
    ripgrep ImageMagick poppler wl-clipboard exiftool \
    mediainfo udisks2 resvg

# ya pkg add ndtoan96/ouch
# ya pkg add Rolv-Apneseth/starship
# ya pkg add yazi-rs/plugins:piper
# ya pkg add yazi-rs/plugins:mount
# ya pkg add boydaihungst/mediainfo

install_if_missing base-devel cmake openssl-devel tbb-devel libvips-devel \
    xcb-util-image-devel extra-cmake-modules wayland-devel wayland-protocols \
    chafa-devel libsixel-devel

build_repo github.com/jstkdng/ueberzugpp \
    "mkdir build && cd build" \
    "cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_X11=OFF -DENABLE_OPENCV=OFF -DENABLE_WAYLAND=ON .." \
    "cmake --build ." \
    "sudo cmake --install ."

echo "Adding .desktop file to $HOME/.local/share/applications"
mkdir -p ~/.local/share/applications
cat <<'EOF' >~/.local/share/applications/yazi.desktop
[Desktop Entry]
Name=Yazi
Icon=system-file-manager
Comment=Blazing fast terminal file manager written in Rust, based on async I/O
Terminal=true
TryExec=yazi
Exec=yazi %u
Type=Application
MimeType=inode/directory
Categories=Utility;Core;System;FileTools;FileManager;ConsoleOnly
Keywords=File;Manager;Explorer;Browser;Launcher
EOF
