general {
  	grace = 0
  	ignore_empty_input = true
  	hide_cursor = true
	disable_loading_bar = false
}

input-field {
    size = 150, 30
    outline_thickness = 2
    dots_size = 0.15 
    dots_spacing = 0.8 
    dots_center = false
    outer_color = rgb(000000)
    inner_color = rgb(ffffff)
    font_color = rgb(000000)
    fade_on_empty = false
    placeholder_text =  
    hide_input = false
    rounding = 0
    check_color = rgb(78a9ff)
    fail_color = rgb(ee5395) 
    fail_text = <i><span foreground='##ee5395'>$FAIL</span></i> 
    fail_transition = 300 
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 

    position = 70, -10
    halign = center
    valign = center
}

background {
    monitor =
    color = rgb(0C0C0C)
	zindex = -7
}

# Main Window
shape {
  size = 500, 200
  color = rgb(282828)
  position = 0, 0
  zindex = -4
}

shape {
  size = 504, 204
  color = rgb(686868)
  position = 0, 0
  zindex = -6
}

shape {
  size = 502, 202
  color = rgb(000000)
  position = 1, -1
  zindex = -5
}

# Title Window
shape {
  size = 490, 30
  color = rgb(484848)
  position = 0, 80
  zindex = -1
}

shape {
  size = 494, 34
  color = rgb(686868)
  position = 0, 80
  zindex = -3
}

shape {
  size = 492, 32
  color = rgb(000000)
  position = 1, 79
  zindex = -2
}

label {
    text = Welcome to Void
    color = rgb(f2f4f8)
    font_size = 13
    font_family = Iosevka Nerd Font Mono

    position = -170, 80
    halign = center
    valign = center
}

label {
    text = Password:
    color = rgb(f2f4f8)
    font_size = 12
    font_family = Iosevka Nerd Font Mono

    position = -70, -10
    halign = center
    valign = center
}

label {
    text = Type a password to log in to Void.
    color = rgb(f2f4f8)
    font_size = 12
    font_family = Iosevka Nerd Font Mono

    position = 30, 40
    halign = center
    valign = center
}

image {
	path = $HOME/.config/hypr/assets/void-white.png
	position = -180, -15
	size = 100
	border_size = 0
}

image {
	path = $HOME/.config/hypr/assets/window-buttons.png
	position = 215, 80
	size = 25
	rounding = 0
	border_size = 0
}
