general {
  	grace = 0
  	ignore_empty_input = true
  	hide_cursor = true
	fractional_scaling = 0
	immediate_render = true
}

animations {
	enabled = false
}

input-field {
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.15 
    dots_spacing = 0.8 
    dots_center = false
    outer_color = rgb(be95ff)
    inner_color = rgba(ffffff00)
    font_color = rgb(f2f4f8)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    rounding = 0
    check_color = rgb(78a9ff)
    fail_color = rgb(ee5395) 
    fail_text = <i><span foreground='##ee5395'>$FAIL</span></i> 
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 

    position = 30, 30
    halign = left
    valign = bottom
    zindex = -6
}

background {
    monitor =
    color = rgb(161616)
	zindex = -7
}

label {
	text =\
<span> _   __     _    __  __   _               </span><br/>\
<span>| | / /__  (_)__/ / / /  (_)__  __ ____ __</span><br/>\
<span>| |/ / _ \/ / _  / / /__/ / _ \/ // /\ \ /</span><br/>\
<span>|___/\___/_/\_,_/ /____/_/_//_/\_,_//_\_\ </span>

    color = rgb(f2f4f8)
    font_size = 13
    font_family = Iosevka Nerd Font Mono

    position = 20, 100
    halign = left
    valign = bottom
}

label {
    text = pass
    color = rgb(be95ff)
    font_size = 12
    font_family = Iosevka Nerd Font Mono

    position = 55, 72
    halign = left
    valign = bottom
}

shape {
	size = 40, 20 
    color = rgb(161616)
    position = 51, 70
    halign = left
    valign = bottom
    zindex = -5
}
