# preload = $HOME/Pictures/gowall/nhk-purple.png
# wallpaper = , $HOME/Pictures/gowall/nhk-purple.png

preload = $HOME/Pictures/gowall/metalheart.jpg
wallpaper = , $HOME/Pictures/gowall/metalheart.jpg
