general {
  	grace = 0
  	ignore_empty_input = true
  	hide_cursor = true
	disable_loading_bar = false
}

input-field {
    monitor =
    size = 400, 50
    outline_thickness = 0
    dots_size = 0.15 
    dots_spacing = 0.8 
    dots_center = false
    dots_rounding = -1 
    outer_color = rgb(220, 224, 229)
    inner_color = rgb(23, 23, 23)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    fade_timeout = 1000 
    placeholder_text = <span foreground='##949494'>password</span> 
    hide_input = false
    rounding = 0
    check_color = rgb(56, 56, 56)
    fail_color = rgb(23, 23, 23) 
    fail_text = <i><span foreground='##949494'>$FAIL</span></i> 
    fail_transition = 300 
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 
    invert_numlock = false 
    swap_font_color = false 

    position = 0, -20
    halign = center
    valign = center
}

background {
    monitor =
    path = screenshot

    blur_passes = 5 
    blur_size = 7
    noise = 0.0117
}

shape {
  monitor =
  size = 120, 50
  color = rgba(238, 83, 150, 1.0)
  rounding = 0
  rotate = 0
  xray = false

  position = -260, -20
  halign = center
  valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(23, 23, 23, 1.0)
    font_size = 20
    font_family = Iosevka Nerd Font Mono

    position = -260, -20
    halign = center
    valign = center
}
