[mgr]
prepend_keymap = [
  { on = "<C-y>", run = 'plugin wl-clipboard', desc = "Copy to clipboard" },

  { on = "C", run = "plugin ouch", desc = "Compress with ouch" },

  { on = "M", run = "plugin mount", desc = "Mount menu" },
]
