[mgr]
show_hidden = true
ratio = [2, 5, 6]
sort_by = "natural"
scrolloff = 8

[preview]
image_delay = 60
ueberzug_offset = [0, -1, 0, 0]

[opener]
edit = [
  { run = '${EDITOR:-hx} "$@"', desc = "Edit", block = true },
  { run = 'sudo -E ${EDITOR:-hx} "$@"', desc = "Edit with root", block = true },
]

open = [{ run = 'xdg-open "$1"', orphan = true, desc = "Open" }]

exif = [
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF" },
]

extract = [{ run = 'ouch d -y "$@"', desc = "Extract here" }]

play = [
  { run = 'mpv "$@"', orphan = true },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = [
    "edit",
    "open",
    "exif",
  ] },
  { mime = "image/*", use = [
    "open",
    "exif",
  ] },
  { mime = "inode/directory", use = [
    "edit",
  ] },
]

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]
prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },

  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
]
