#!/usr/bin/env bash

exclude=(
    "$(basename "$0")"
    "common"
    "extra"
    "unstow"
)

deps=()
while IFS= read -r file; do
    base_name="$(basename "$file")"
    if [[ ! " ${exclude[*]} " =~ $base_name ]]; then
        deps+=("dots/$base_name")
    fi
done < <(find tasks/dots -maxdepth 1 -type f)

source tasks/common

echo "Running these dotfile tasks:"
printf "%s\n" "${deps[@]##*/}"

if ! confirm "Run all dotfile tasks?" "N"; then
    exit 1
fi

# Task
resolve_deps
