#!/usr/bin/env bash

cleanup() {
    echo "Exiting..."
    exit 1
}

trap cleanup SIGINT

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This script cannot be executed directly"
    exit 1
fi

stow_package() {
    if ! command -v stow >/dev/null; then
        echo "Stow command not found. Install stow and rerun the task" >&2
        exit 1
    fi

    echo -e "Stowing package: $1"
    stow --verbose --restow --target="$HOME" $1
}
