#!/usr/bin/env bash

source tasks/common

stow_package() {
    if ! command -v stow >/dev/null; then
        if confirm "Stow command not found. Install it using xbps?" "Y"; then
            install_if_missing stow
        else
            echo "Dotfile tasks require stow"
            exit 1
        fi
    fi

    if ! stow -n --target="$HOME" "$1" &>/dev/null; then
        echo "You already have $1 config files!"
        echo "Backup/remove them and try again"
        exit 1
    fi

    echo -e "Stowing package: $1"
    stow --verbose --restow --target="$HOME" "$1"
}
