#!/usr/bin/env bash

deps=()

source tasks/common
resolve_deps

# Task
if ! command -v stow >/dev/null; then
    if confirm "Stow command not found. Install it using xbps?" "Y"; then
        install_if_missing stow
    else
        echo "Dotfile tasks require stow"
        exit 1
    fi
fi

read -rp "Enter package to remove: " unstow

if [ -z "$unstow" ]; then
    echo "No package specified"
    exit 1
fi

echo -e "\nRemoving package: $unstow"
stow --delete --target="$HOME" "$unstow"
