#!/usr/bin/env bash

deps=()

source tasks/common
resolve_deps

# Task
if ! command -v stow >/dev/null; then
    echo "Stow command not found. Install stow and rerun the task" >&2
    exit 1
fi

read -p "Enter your wallpaper folder path (default is $HOME/Pictures/Wallpaper): " wpfolder

if [ -z "$wpfolder" ]; then
    wpfolder="$HOME/Pictures/Wallpaper"
    echo "Using default location"
fi

echo -e "\nStowing package: wallpaper to: $wpfolder"
stow --verbose --adopt --target="$wpfolder" wallpaper
