#!/usr/bin/env bash

deps=()

source tasks/common
resolve_deps

# Task
if ! command -v stow >/dev/null; then
    if confirm "Stow command not found. Install it using xbps?" "Y"; then
        install_if_missing stow
    else
        echo "Dotfile tasks require stow"
        exit 1
    fi
fi

read -p "Enter your wallpaper folder path (default is $HOME/Pictures/Wallpaper): " wpfolder

if [ -z "$wpfolder" ]; then
    wpfolder="$HOME/Pictures/Wallpaper"
    echo "Using default location"
fi

echo -e "\nStowing package: wallpaper to: $wpfolder"
stow --verbose --adopt --target="$wpfolder" wallpaper
